/* Generated by @voxgig/sdkgen. Do not edit. */
'use strict'

const { describe, it, before } = require('node:test')
const assert = require('node:assert')

const Seneca = require('seneca')

const EvervaultProvider = require('../dist/evervault-provider')
const EvervaultProviderDoc = require('../dist/EvervaultProvider-doc')

const SenecaMsgTest = require('seneca-msg-test')
const { Maintain } = require('@seneca/maintain')

const { SEED } = require('./seed')

const BasicMessages = require('../dist-test/basic.messages')


describe('evervault-provider', () => {

  it('happy', async () => {
    assert.notEqual(EvervaultProvider, undefined)
    assert.notEqual(EvervaultProviderDoc, undefined)

    const seneca = await makeSeneca()

    assert.partialDeepStrictEqual(
      await seneca.post('sys:provider,provider:evervault,get:info'),
      {
        ok: true,
        name: 'evervault',
      },
    )
  })


  it('messages', async () => {
    const seneca = await makeSeneca()
    await SenecaMsgTest(seneca, BasicMessages)()
  })


  it('sdk-export', async () => {
    const seneca = await makeSeneca()
    const sdk = seneca.export('EvervaultProvider/sdk')()

    assert.equal(typeof sdk.Card, 'function')
  })


  it('card-load', async () => {
    const seneca = await makeSeneca()
    const found = await seneca
      .entity('provider/evervault/card')
      .load$('card0')

    assert.equal(found.id, 'card0')
    assert.equal(
      found.canon$({ string: true }),
      'provider/evervault/card',
    )
  })


  // A 404 from a single-item read is an ordinary "not found" answer, not a
  // failure: the provider turns it into null rather than letting the SDK
  // throw.
  it('card-load-missing', async () => {
    const seneca = await makeSeneca()
    const missing = await seneca
      .entity('provider/evervault/card')
      .load$('nosuchcard')

    assert.equal(missing, null)
  })


  it('card-crud', async () => {
    const seneca = await makeSeneca()
    const ent = seneca.entity('provider/evervault/card')

    // Seneca's convention: an entity WITHOUT an id is a create. The API
    // assigns the id itself, so the saved record comes back with one it chose.
    const made = await ent.make$({ expiry: {}, month: 'crud-month', number: 'crud-number', year: 'crud-year' }).save$()

    assert.ok(null != made.id)
    assert.equal(
      made.canon$({ string: true }),
      'provider/evervault/card',
    )

    const id = made.id

    try {
      const loaded = await ent.load$({ id: id })
      assert.equal(loaded.id, id)

      // An entity CARRYING an id is an update, not a second create.
      loaded.month = 'crud-month-2'
      const updated = await loaded.save$()

      assert.equal(updated.id, id)
      assert.equal(updated.month, 'crud-month-2')

      const reloaded = await ent.load$({ id: id })
      assert.equal(reloaded.month, 'crud-month-2')
    }
    finally {
      // Always clean up. The mock and the server both hold data for the
      // process lifetime, so a leaked record changes what later tests see.
      await ent.remove$({ id: id })
    }

    // remove is real: the record is gone, and reading it is an ordinary
    // not-found rather than an error.
    assert.equal(await ent.load$({ id: id }), null)
  })


  it('maintain', async () => {
    const exclude = []

    // check_default proves the default branch is main by looking for
    // [branch "main"] in .git/config. Only a branch checkout records that
    // section: a pull_request build checks out the merge ref, and the
    // publish build checks out a tag as a detached HEAD. Neither says
    // anything about what the default branch is, so skip rather than fail.
    if ('pull_request' === process.env.GITHUB_EVENT_NAME ||
        'tag' === process.env.GITHUB_REF_TYPE) {
      exclude.push('check_default')
    }

    // url_pkgjson locates package.json by comparing process.cwd() + '/package.json'
    // against a path found with Filehound. On Windows those are the same file
    // spelt with different separators, so the url is never read.
    if ('win32' === process.platform) {
      exclude.push('url_pkgjson')
    }

    await Maintain({ exclude })
  })

})


// Default to the SDK's offline mock transport, seeded from ./seed.
async function makeSeneca(pluginopts) {
  pluginopts = pluginopts || { test: true, testopts: SEED }

  const seneca = Seneca({ legacy: false })
    .test()
    .use('promisify')
    .use('entity')
    .use('env', {
      // Declared so the provider convention is exercised, and defaulted so
      // the suite runs with nothing configured.
      var: {
        $EVERVAULT_APIKEY: '',
      },
    })
    .use('provider', {
      provider: {
        evervault: {
          keys: {
            apikey: { value: '$EVERVAULT_APIKEY' },
          },
        },
      },
    })
    .use(EvervaultProvider, pluginopts)

  return seneca.ready()
}
