/* Generated by @voxgig/sdkgen. Do not edit. */
'use strict'

// Seed data for the SDK's offline mock transport, so the entity tests
// exercise real code paths without a server.
const SEED = {
  entity: {
    card: {
      card0: {"expiry":{},"month":"month0","number":"number0","year":"year0"},
      card1: {"expiry":{},"month":"month1","number":"number1","year":"year1"},
    },
  },
}

module.exports = { SEED }
