/* Generated by @voxgig/sdkgen. Do not edit. */

const Pkg = require('../package.json')

const { EvervaultSDK } = require('@voxgig-sdk/evervault')

const SdkPkg = require('@voxgig-sdk/evervault/package.json')


type EvervaultProviderOptions = {
  // Options passed straight to the EvervaultSDK constructor,
  // most usefully `base` to point at a server.
  sdk?: Record<string, any>

  // Run the SDK in offline test mode (in-memory mock transport).
  test?: boolean

  // Test feature options, e.g. {entity: {card: {...}}} to
  // seed the mock with data. Only used when `test` is true.
  testopts?: Record<string, any>
}


function EvervaultProvider(this: any, options: EvervaultProviderOptions) {
  const seneca: any = this

  const entityBuilder = this.export('provider/entityBuilder')

  seneca.message('sys:provider,provider:evervault,get:info', get_info)

  async function get_info(this: any, _msg: any) {
    return {
      ok: true,
      name: 'evervault',
      version: Pkg.version,
      sdk: {
        name: '@voxgig-sdk/evervault',
        version: SdkPkg.version,
      },
    }
  }


  // Every SDK operation resolves to an SDK ENTITY rather than raw data (a
  // removed record included: it comes back marked deleted, still holding what
  // it held). Seneca wants plain data, which the entity hands over through
  // data().
  function plain(res: any) {
    return null == res ? res : res.data()
  }


  // Seneca query directives (sort$, limit$, ...) are for the store, not the
  // API, so they must not reach the SDK as match fields.
  function cleanq(q: any) {
    const out: any = {}
    for (const k in (q || {})) {
      if (!k.endsWith('$')) {
        out[k] = q[k]
      }
    }
    return out
  }


  // The SDK throws on any non-2xx. A 404 from a single-item read is an
  // ordinary "not found" answer rather than a failure, so return null and let
  // everything else propagate. SDK errors carry the HTTP status at the top
  // level, so ask them rather than digging into `result`.
  async function ornull(action: () => Promise<any>) {
    try {
      return await action()
    }
    catch (e: any) {
      if (true === e?.notFound) {
        return null
      }
      throw e
    }
  }

  const entity: any = {
    card: {
      cmd: {
        load: { action: (undefined as any) },
        save: { action: (undefined as any) },
        remove: { action: (undefined as any) },
      },
    },

  }


  entity.card.cmd.load.action =
    async function load_card(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const res = await ornull(() => this.shared.sdk.Card().load({ id: q.id }))
      return null == res ? null : entize(plain(res))
    }


  entity.card.cmd.save.action =
    async function save_card(this: any, entize: any, msg: any) {
      const data = msg.ent.data$(false)
      const sdk = this.shared.sdk

      const res = await sdk.Card().create(data)

      return entize(plain(res))
    }


  entity.card.cmd.remove.action =
    async function remove_card(this: any, _entize: any, msg: any) {
      const q = cleanq(msg.q)
      await ornull(() => this.shared.sdk.Card().remove({ id: q.id }))
      return null
    }


  entityBuilder(this, {
    provider: {
      name: 'evervault',
    },
    entity
  })


  seneca.prepare(async function(this: any) {
    const sdkopts: any = Object.assign({}, options.sdk)

    // The provider convention carries credentials, so honour an `apikey`
    // when one is configured and stay quiet when it is not.
    const res = await this.post('sys:provider,get:keymap,provider:evervault')
    const apikey = res?.keymap?.apikey?.value

    // Hand the credential to the SDK as `apikey`, NOT as an authorization
    // HEADER. The SDK's own auth stage owns that header: it reads
    // `options.apikey`, and on every path where it finds none it DELETES
    // `authorization` before the request goes out. A provider that set the
    // header itself was therefore never authenticated — the SDK stripped the
    // very thing it had just written, on every call, silently. The SDK also
    // owns the scheme prefix, which is resolved from the API definition
    // rather than assumed to be `Bearer`.
    if (null != apikey && '' !== apikey) {
      sdkopts.apikey = apikey
    }

    this.shared.sdk = options.test
      ? EvervaultSDK.test(options.testopts || {}, sdkopts)
      : new EvervaultSDK(sdkopts)
  })


  return {
    exports: {
      sdk: () => this.shared.sdk,
    },
  }
}


// Default options.
const defaults: EvervaultProviderOptions = {
  sdk: {},
  test: false,
  testopts: {},
}

Object.assign(EvervaultProvider, { defaults })

export default EvervaultProvider

if ('undefined' !== typeof module) {
  module.exports = EvervaultProvider
}
